### ISSUE TITLE
Extrahovat CSS do samostatného souboru

### ISSUE THREAD

**Issue by tenhobi** [fnx-io/dartlang.cz#3]
Možná by stálo za to extrahovat CSS z HTML do samostatného CSS souboru, kvůli budoucím modifikacím a možnosti importování aj z jiných souborů. 

Mohu udělat.

**Comment by Tomucha** [comment]
Klidně, do toho. Ale žádnej gulp nebo tak 😀 Pure Dart!

**Comment by tenhobi** [comment]
Btw. jsem koukal, že vývojáři Sass preprocesoru to přepisují do Dartu, což bude hlavní verze. Momentálně mají Ruby verzi (tu tuším opustí) a k tomu mají paralelně libsass (to je tuším v C či C++). Někde jsem tuším četl, že sice je ta libsass verze trochu rychlejší oproti Dartu, ale Dart chtějí hlavně kvůli jeho jednoduchosti na rozšiřování.

https://github.com/sass/dart-sass

Ale pro začátek by stačilo jen pure CSS. :-)

**Comment by Tomucha** [comment]
... nikomu to nerikej, ale ta Sass vyvojarka co to dela je soucasne jeden z vyvojaru Dartu :-)
