### ISSUE TITLE
Ukázky použití

### ISSUE THREAD

**Issue by tenhobi** [fnx-io/dartlang.cz#4]
Co třeba přidat nějaké ukázky použití, případně nějaký menší Dart tutoriál?

(mohu pomoci)

**Comment by Tomucha** [comment]
To si musím rozmyslet, ale asi ne-e.

Spíš bych tam přidal sekci s odkazy na české zdroje - články, ta tvoje soutěž a tak. Větší obsah bych tu netvořil, protože by ho tu nikdo nenašel. Pokud si myslíš, že bys uměl sesmolit Dart tutoriál, proč to nedat na zdroják? Tak to bude mít větší impact.

**Comment by tenhobi** [comment]
Pravda. Pokud tedy něco, tak asi to dát někam na ITnetwork, zdroják, či podobné stránky, kde je větší dosah.

Sekce s odkazy na výukové věci je dobrý nápad. Další by mohl být ten seznam lidí (společností), co Dart používají v Česku.

**Comment by Tomucha** [comment]
Jo, to bych tam chtěl, ale zatim mám jen 5 věcí což je málo :-)

**Comment by Tomucha** [comment]
A už mám 8 :-) To už je docela důstojný.
