### ISSUE TITLE
Vylepšení repozitáře

### ISSUE THREAD

**Issue by tenhobi** [fnx-io/dartlang.cz#5]
- [x] napsat README.md
- [x] přidat popis do hlavičky repozitáře
- [x] přidat repoziráři tagy
- [x] disabnout wiki – není potřeba
- [x] uzamknout master branch (pro jistotu)

**Comment by Tomucha** [comment]
Nějak nevím co je zamykání branchí, ale koukám, že by např. pull requesty museli procházet nějakým review - to je asi u tohodle projektu poněkud koána na vrabce.

**Comment by tenhobi** [comment]
Hmm, já myslím, že ten review je nastavitelný. Uzamknutí by mělo být (nebo bylo) čistě proto, abys nemohl dělat force pushe a tím nesmazat obsah.

**Comment by Tomucha** [comment]
Ok, je to tam. Ale běda ti, jestli mě ta věc bude teď buzerovat nějakejma kravinama! :-)

**Comment by tenhobi** [comment]
![screenshot_26](https://cloud.githubusercontent.com/assets/5287596/23986922/fc97a8b8-0a26-11e7-8b20-98d2012179ce.png)

Tam to je právě takto. Červený zablokuje force-pushe a nemůžeš větev smazat. Modrý by přidal to, že vše musí jít přes pull requesty a musí to mít review. A zelený netuším na co je, asi něco jako že musíš vytvářet do separátních branchí, které pak merguješ do masteru.
