### ISSUE TITLE
Analysis options + CI kontrola

### ISSUE THREAD

**Issue by tenhobi** [fnx-io/dartlang.cz#7]
Nebudeme chtít nějaké přísnější analysis options, jako mám např. na https://github.com/HoBi/dart-tanks/blob/master/analysis_options.yaml – hlavně tam je nastaveno, aby se všude používaly typy?

A na to se pak dá napojit CI, které to dokáže kontrolovat. Defaultně to taky spustí všechny testy a stáhne vše z pub, viz https://docs.travis-ci.com/user/languages/dart/.

Myslím, že je to dobré mít už kvůli budoucnosti, protože nikdy nevíš, jak se projekt může rozšířit. A hlavně to pomůže mít unifikovaný kód. 🥇

**Comment by tenhobi** [comment]
A samozřejmě se na to dá také napojit deploy, což je big plus. 😺

**Comment by Tomucha** [comment]
Nechci to zase moc komplikovat. Defaultni priklady ze stagehand taky nemaji strong mode zapnuty. Nechci aby to pusobilo moc exoticky a rigidne ... Ale budiz, kdyz posles pull request, tak to tam dam.
